# .github/workflows/deploy.yml
name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main # The branch you push your source code to

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important for pushing to gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build # Or `astro build` if you don't have a build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # A popular action for deploying to GH Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The directory containing your built site
          # If your repo is a User/Org page (e.g., username.github.io),
          # set cname: 'username.github.io' and remove the `base` in astro.config.mjs
          # if you want root domain. Otherwise, keep `base` for project pages.
